spring.application.name=productos-api

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/techlabdb
spring.datasource.username=root
spring.datasource.password=******

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true